### ISSUE TITLE
Setting up Eclipse

### ISSUE THREAD

**Issue by AdySan** [aanon4/HomeKit#1]
I'm setting up Eclipse/GCC toolchain first time, so please help me out a little please.

I've walked through most of [this](https://devzone.nordicsemi.com/tutorials/7/) manual. I can get examples with Makefiles to build in command line. This project doesn't seem to have a Makefile, only an Eclipse project. When I import the project into eclipse, I'm not sure how to point Eclipse to the SDK location. It can't find any of the SDK headers like ble.h

https://www.dropbox.com/s/iyatk3d1qumfmgl/Screenshot%202016-03-06%2017.30.52.png?dl=0

I also see [references](https://github.com/aanon4/HomeKit/blob/master/.project#L95) to local paths.

**Comment by AdySan** [comment]
Some progress, I'm down to two errors 

Description Resource    Path    Location    Type
/Users/adityatannu/Documents/Packages/.cache/NordicSemiconductor.nRF_DeviceFamilyPack.8.5.0.pdsc (No such file or directory), file: NordicSemiconductor.nRF_DeviceFamilyPack.8.5.0.pdsc         -   Packs

Description Resource    Path    Location    Type
make: **\* No rule to make target `/Users/adityatannu/nrf51_sdk/components/libraries/gpiote/app_gpiote_fast_detect.c', needed by`src/nrf51/nrf51_sdk/app_gpiote_fast_detect.o'.  Stop.  HomeKit         C/C++ Problem

**Comment by chrgm** [comment]
Did you managed to build the project? 

I tried a few hours to build it with Eclipse, but it won't built.
Then I tried it with a Makefile of the `ble_app_template` example applications, which worked fine until there occurred some linker errors which I could resolve.
But then I ended up in some compiler errors in the file `crypto/srp/bn_mul.h`.
Could you share, how you managed to build the project with the "standard" Eclipse GCC Toolchain?

**Comment by AdySan** [comment]
@Christian-GM Well, yes I did manage to build it with @KhaosT's help. I've since then got access to Nordic's HK SDK, so that makes things much easier. 

Now that I have a slightly better grasp of Eclipse GCC Toolchain, I should give this a try again sometime.

**Comment by danielei** [comment]
Hi,
I have the same problem:
make: **\* No rule to make target /Users/adityatannu/nrf51_sdk/components/libraries/gpiote/app_gpiote_fast_detect.c', needed bysrc/nrf51/nrf51_sdk/app_gpiote_fast_detect.o'. Stop. HomeKit C/C++ Problem

How did you fix it ?

Thanks,
Danny

**Comment by chrgm** [comment]
Hi Danny, 

unfortunately I could not fix it. I could build the example applications but when I want to build this BLE project it failes.
If you solved the problem let me know it.

Chris

**Comment by maccoylton** [comment]
I was able to build it using Eclipse and SDK 9, other version of the SDK I tried did not work as there were either files missing or files in different directories than expected.  

When you set up your project, import the SDK into the same workspace using the import function. I had to also manually edit the .project file to point the Homekit project to the right place for the SDK.
