### ISSUE TITLE
nRF52 config

### ISSUE THREAD

**Issue by abishekh** [aanon4/HomeKit#2]
I'd like to try this on a [nRF52 dev kit](http://www.mouser.com/new/nordicsemiconductor/nordic-nrf52-dk/) . Are there any special config changes to build for nRF52 ?

**Comment by AdySan** [comment]
I've got it to build for nRF52, it doesn't seem to build fine and merge with SD s132 however it's crashing at some point, haven't got a chance to debug it yet. Please post your progress if you do get it to work.

**Comment by AdySan** [comment]
I mean it _does_ build fine.
